// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwacwevimpifqvwpxquq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3YWN3ZXZpbXBpZnF2d3B4cXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTc3OTksImV4cCI6MjA2NzU3Mzc5OX0.mvICp3bg-UyECXa_UBBqSiFQrMsjb3SYFZRfdgq-cfw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});